### ISSUE TITLE
More BitDay images

### ISSUE THREAD

**Issue by CaviaPorcellus** [chenasraf/BitDay-Linux#1]
This should be updated with the new set of images (there are now early/mid/late morning and evening images). 

Thanks.

**Comment by chenasraf** [comment]
Is this the latest updated pack? http://danny.care/bitday/download/

If so, I will update soon (following day/two)

**Comment by chenasraf** [comment]
@aibaraiduas please check the new version - honestly I'm not using Linux anymore, so I can't really test the hours - let me know if there are any issues and I'll do my best to fix them :) thanks!
